# Generated by Django 2.1.5 on 2019-02-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_post_is_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='session_id',
            field=models.CharField(default='no session', max_length=100),
        ),
    ]
