# Generated by Django 2.1.5 on 2019-02-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_post_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='session_id',
        ),
    ]
