# Generated by Django 2.1.5 on 2019-02-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_remove_post_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='session_id',
            field=models.CharField(default='no session', max_length=100),
        ),
    ]
